# Training configuration
GPU: [0, 1]

VERBOSE: False

SWINUNET:
  IMG_SIZE: 128
  PATCH_SIZE: 4
  WIN_SIZE: 8
  EMB_DIM: 96
  DEPTH_EN: [8, 8, 8, 8]
  HEAD_NUM: [8, 8, 8, 8]
  MLP_RATIO: 4.0
  QKV_BIAS: True
  QK_SCALE: 8
  DROP_RATE: 0.
  ATTN_DROP_RATE: 0.1
  DROP_PATH_RATE: 0.1
  APE: False
  PATCH_NORM: True
  USE_CHECKPOINTS: False
  FINAL_UPSAMPLE: 'Dual up-sample'


# Optimization arguments.
OPTIM:
  BATCH: 128
  EPOCHS: 50000
  LR_INITIAL: 2e-3
  LR_MIN: 1e-6

TRAINING:
  VAL_AFTER_EVERY: 10
  SAVE_LOG: 10
  TRAIN_PS: 128
  VAL_PS: 128
  TRAIN_DIR: "/nfsdata/share/ssl_legacy/ssl_legacyA/file/south-train/"
  VAL_DIR: "/share2/fumingxiang/BGS_cut_v1/raw/"            # path to validation data

TESTING:
  VAL_AFTER_EVERY: 10
  VAL_PS: 128
  DATA_TYPE: "FITS"
  VAL_DIR: "./data/FITS"
